### ISSUE TITLE
Test content included in sample Alloy site database

### ISSUE THREAD

**Issue by daniel-isaacs** [episerver/content-templates#41]
After spinning up a new Alloy site using the templates, there is a test page with test content included in the database:

![42b43b10-8040-41b1-b886-113d80e95e8b](https://user-images.githubusercontent.com/12244947/176500395-bccceba3-592a-44f1-9a3a-f14e8c442268.jpg)

To recreate:

1. Create a new site with: 
_dotnet new epi-alloy-mvc_
2. Run the site

**Comment by LucGosso** [comment]
Pretty good feature i’d say, just remove the pagetype in code if you dont like it? I guess epi internally uses it for testing new versions.
